drop table if exists movie CASCADE;
create table movie
(
    id bigint generated by default as identity,
    created_at date,
    updated_at date,
    code_fims varchar(50) not null,
    title varchar(255) not null,
    synopsis text,
    release_date date,
    prod_year integer,
    primary key (id)
);